services:
  web-app:
    build: ./src/FitBurger.WebApp
    image: "fitburger.com/app:latest"
    container_name: web-app
    ports:
      - "8000:80"
    networks:
      - backend 
  sql:
    build: ./database
    image: "fitburger.com/sql:latest"
    container_name: sql-server
    ports:
      - "1433:1433"
    networks:
      - backend

networks:
  backend:
    name: backend